# Generated by Django 4.2.7 on 2023-11-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_key', models.IntegerField(primary_key=True, serialize=False)),
                ('created_ts', models.DateField()),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('jalali_created_date', models.CharField(max_length=10)),
                ('jalali_year', models.SmallIntegerField()),
                ('jalali_month', models.SmallIntegerField()),
                ('jalali_day', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Dim.Date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimDate1',
            fields=[
                ('date_key', models.IntegerField(primary_key=True, serialize=False)),
                ('created_ts', models.DateField(blank=True, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, null=True)),
                ('day', models.SmallIntegerField(blank=True, null=True)),
                ('jalali_created_date', models.CharField(max_length=10)),
                ('jalali_year', models.SmallIntegerField(blank=True, null=True)),
                ('jalali_month', models.SmallIntegerField(blank=True, null=True)),
                ('jalali_day', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dim.Date1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimEstimation',
            fields=[
                ('estimation_key', models.AutoField(primary_key=True, serialize=False)),
                ('estimated_time_d_id', models.CharField(max_length=20)),
                ('activity_part', models.CharField(max_length=50)),
                ('job_rasteh', models.CharField(max_length=50)),
                ('estimated_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'Dim.Estimation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimJob',
            fields=[
                ('job_key', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.SmallIntegerField()),
                ('rasteh_id', models.SmallIntegerField()),
                ('job_rasteh', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Dim.Job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProject',
            fields=[
                ('project_key', models.AutoField(primary_key=True, serialize=False)),
                ('project_detail_id', models.IntegerField()),
                ('project_kind', models.CharField(max_length=100)),
                ('cost_center', models.CharField(max_length=555)),
                ('project_name', models.CharField(max_length=255)),
                ('project_cost', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('project_course', models.SmallIntegerField(blank=True, null=True)),
                ('signer_user', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Dim.Project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimStatus',
            fields=[
                ('status_key', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Dim.Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimUser',
            fields=[
                ('user_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_job_id', models.SmallIntegerField()),
                ('user_id', models.SmallIntegerField()),
                ('user_firstname', models.CharField(max_length=30)),
                ('user_lastname', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'Dim.User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProjectactivity',
            fields=[
                ('key_fact_pact', models.AutoField(primary_key=True, serialize=False)),
                ('activity_part', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('job_rasteh', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('work_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'Fact.ProjectActivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactUseractivity',
            fields=[
                ('key_fact_uact', models.AutoField(primary_key=True, serialize=False)),
                ('sheet_h_id', models.IntegerField()),
                ('training_minutes', models.IntegerField()),
                ('overwork_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'Fact.UserActivity',
                'managed': False,
            },
        ),
    ]
